# Generated by Django 4.0.1 on 2022-04-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity', models.IntegerField()),
                ('hour_of_day', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UsageRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwh_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hour_of_day', models.IntegerField()),
                ('is_weekday', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendly_name', models.CharField(max_length=255)),
                ('charging_plan', models.CharField(choices=[('emissions_plan', 'Emissions Charging Plan'), ('money_plan', 'Money Charging Plan')], max_length=100)),
                ('charger_kw', models.DecimalField(decimal_places=2, max_digits=5)),
                ('battery_capacity', models.IntegerField()),
                ('target_battery_pct', models.IntegerField()),
                ('current_battery_pct', models.IntegerField()),
            ],
        ),
    ]
