# Generated by Django 4.0.3 on 2022-04-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_seed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('should_charge', models.BooleanField()),
                ('estimated_battery_pct', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
    ]
