# Generated by Django 4.0.3 on 2022-04-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='charging_plan',
            field=models.CharField(choices=[('emissions_plan', 'Emissions Charging Plan'), ('money_plan', 'Money Charging Plan'), ('fast_plan', 'Fast Charging Plan')], max_length=100),
        ),
    ]
